### ISSUE TITLE
README: add link to demos

### ISSUE THREAD

**Issue by dolmen** [segfault87/ldraw.rs#1]
From the [Hacker News post](https://news.ycombinator.com/item?id=20990135), those demos would be helpful to show in the README:
* https://segfault87.github.io/ldraw-rs-preview/#models/car.ldr
* https://segfault87.github.io/ldraw-rs-preview/#models/6973.ldr

**Comment by segfault87** [comment]
Sounds good. I'm going to completely rewrite README and will attach link to demos.

**Comment by segfault87** [comment]
Added link to demo pages.
